### ISSUE TITLE
gologin does not work

### ISSUE THREAD

**Issue by FeelsBadMan1** [gologinapp/gologin#10]
Hello, im able to use gologin with no issures manually. However when i try to use the code then run it the browser just dont start and i get a error I made everything correct, i gave the right apikey, the correct profileid and the correct chromedriver path. another thing is the profileid. i dont know the id each time if i wanna send the done projects to sum guys they not want to put a id each time. Im using it on Python.
```
executablePath C:\Users\Administrator\.gologin/browser/orbita-browser/chrome
Traceback (most recent call last):
  File "D:/my_python_projects/gologin_selenium/mycode.py", line 16, in <module>
    debugger_addy = gl.start()
  File "D:\my_python_projects\gologin_selenium\gologin.py", line 88, in start
    profile_path = self.createStartup()
  File "D:\my_python_projects\gologin_selenium\gologin.py", line 348, in createStartup
    self.profile = self.getProfile()
  File "D:\my_python_projects\gologin_selenium\gologin.py", line 176, in getProfile
    'Authorization': 'Bearer ' + self.access_token,
TypeError: can only concatenate str (not "NoneType") to str

Process finished with exit code 1
```

**Comment by ejames17** [comment]
@FeelsBadMan1  sounds like you need to store the profile ID somewhere. Im using Node with mongo we use something like this 

`const  createProfileForWorker = async (num = 0, startWorkerNum = 0) => {

    return Promise.map(new Array(num), async () => {

        const os = ['lin', 'mac', 'win', 'android'];

        const GL = new GoLogin({
            token: GLTOKEN,
        });
        const i = GL.getRandomInt(0, 3);

        const profileId = await GL.create({os: os[i]});
        const profileName = (process.env.NODE_ENV === 'production') ? `BROWSER-INSTANCE-${startWorkerNum}-PROD` : `BROWSER-INSTANCE-${startWorkerNum}-DEV`;
        const profileToUpdate = {
            id: profileId,
            notes: JSON.stringify({ workerNum: startWorkerNum, environment: process.env.NODE_ENV, sessionControl: false, storage: startWorkerNum % 5 === 0}),
            name: profileName,
            storage: {
                session: startWorkerNum % 5 === 0
            }
        };

        profileToUpdate.proxy = proxyService.getProxyConfigs({proxyType: 'NETNUT'},  false);

        startWorkerNum += 1;
        return GL.update(profileToUpdate);

    })


}`

**Comment by Mixolap** [comment]
check 'token' param in gologin constructor, also you may set access_token manualy in GoLogin object.
