### ISSUE TITLE
getTimezoneWithSocks timeout

### ISSUE THREAD

**Issue by perioh** [gologinapp/gologin#11]
If account is using socks5, than there is an Exception 
`C:\Users\Administrator\node_modules\gologin\gologin.js:513
        reject(new Error('Timeout exceeded'));
               ^

Error: Timeout exceeded
    at Timeout._onTimeout (C:\Users\Administrator\node_modules\gologin\gologin.js:513:16)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
`

With http proxy this never happens

**Comment by AlwaysJoy** [comment]
Same issue.

**Comment by chudilka1** [comment]
+, pls do smth with it

**Comment by AlwaysJoy** [comment]
Gologin is not recommended, they never explain anything about technical issues.

**Comment by NephilimLord** [comment]
Fix in 1.0.27 package version
