### ISSUE TITLE
Browser Checker Deletes Folder twice causing an ENOENT no such file or directory found on Darwin 

### ISSUE THREAD

**Issue by ejames17** [gologinapp/gologin#13]
https://github.com/gologinapp/gologin/blob/4e20b6b5322fa68e6b0ad8870a72e0f9ad90e7dd/browser-checker.js#L97

This function first deletes the files in the gologin browser directory.

Then there is a darwin platform check in the replace browser function
https://github.com/gologinapp/gologin/blob/4e20b6b5322fa68e6b0ad8870a72e0f9ad90e7dd/browser-checker.js#L263

Which tries to delete the files again which was already deleted by https://github.com/gologinapp/gologin/blob/4e20b6b5322fa68e6b0ad8870a72e0f9ad90e7dd/browser-checker.js#L97

Which causes an error ENOENT no such file or directory found.

**Comment by molfar** [comment]
Have exactly the same bug with lates version

**Comment by NephilimLord** [comment]
Package has been updated few times. If problems left please open new issue
