### ISSUE TITLE
Cant use api

### ISSUE THREAD

**Issue by moygospadin** [gologinapp/gologin#133]
System
Linux
Code 
```
 const GL = new GoLogin({
    token:'myToken'  ,
     profile_id: 'profile_id',
  });

```
Api token from this page 
![image](https://github.com/gologinapp/gologin/assets/60549587/59264639-2313-4bff-bf6b-32cb41a87356)
Profile id from this page 
![image](https://github.com/gologinapp/gologin/assets/60549587/d943210e-0748-42bd-a261-324adc122990)
Got this error
ENOENT: no such file or directory, open ](race: Error: ENOENT: no such file or directory, open '/tmp/gologin_profile_66611321e0a4814db3850c71/Default/Preferences')

**Comment by NephilimLord** [comment]
Fixed
