### ISSUE TITLE
Error running on Selenium Mac

### ISSUE THREAD

**Issue by shehrozkapoor** [gologinapp/gologin#21]
I am trying to run the gologin on selenium and it giving me error on the executable path..it does not find the file orbita-browser/chrome and I checked in that folder also no folder found with that name.
![Screenshot 2021-10-30 at 4 48 12 PM](https://user-images.githubusercontent.com/59894229/139531682-8737061c-0f6c-439a-ba5f-5299b32a9c23.png)
th

**Comment by Mixolap** [comment]
Is installed app from https://app.gologin.com/?

**Comment by shehrozkapoor** [comment]
Yes i have download it directly for mac

**Comment by NephilimLord** [comment]
Package have been updated few times. Please open new issue if problem's left
