### ISSUE TITLE
Headless with proxy page not render.

### ISSUE THREAD

**Issue by bacnt2412** [gologinapp/gologin#24]
I use proxy + no headless is fine.!
But proxy + headless the page is not loaded. background white

**Comment by pango-lier** [comment]
Do you have a solution to this problem? 
I had the same problem ?
i use linux ubuntu OS and orbita-browser

**Comment by Mixolap** [comment]
try add delay after browser.newPage()

**Comment by bacnt2412** [comment]
I tried sleep 10s after newpage, but the error still occurs. It seems that the proxy is faulty but when there is no headless, it works normally Error: net::ERR_SOCKS_CONNECTION_FAILED at https://www.amazon.com/ap/signin?

**Comment by pango-lier** [comment]
I add delay after browser.newPage() but not work .
Log-error:
 SQLITE_ERROR: table cookies has no column named top_frame_site_key
 
 Version
 go-login:1.0.29
 puppeteer-core:10.4.0
 node :v14.18.2
 ubuntu OS  20
 orbita-browser :5.02

**Comment by Vaviloff** [comment]
```
SQLITE_ERROR:` table cookies has no column named top_frame_site_key
```
Looks like this profile is updated for the new version of Orbita browser but you're using an older binary.

**Comment by pango-lier** [comment]
How to downgrade or install a specific version of Orbita browser or other solution .
thanks

**Comment by pango-lier** [comment]
when i run orbitar by comand line :
`
./chrome --headless  --no-sandbox
`
then error
`
ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is
`

**Comment by Vaviloff** [comment]
@pango-lier Looks like [there are some ways](https://www.google.com/search?q=Passthrough+is+not+supported%2C+GL+is+swiftshader) to deal with it.

**Comment by pango-lier** [comment]
Thanks . I not found solution for this problem .

**Comment by Vaviloff** [comment]
> Thanks . I not found solution for this problem .  

@pango-lier You should have told us what you've tried. 

Also since it is not specifically a Gologin problem, why not try your chances asking at [Stackoverflow](https://stackoverflow.com/questions/tagged/puppeteer%2bor%2bplaywright?tab=Newest)?

**Comment by gentrith78** [comment]
Hello  any solution  for this  problem?
