### ISSUE TITLE
Error: Look like you are spoofing your location when access iphey.com

### ISSUE THREAD

**Issue by huynhtai29** [gologinapp/gologin#27]
I run success application selenium-gologin.py but when access to iphey.com to test profile.
Error "Look like you are spoofing your location" was happens.
This issue does not happen when running the application Gologin.
My OS work: Ubuntu 20.04
The image of this issue:
![Screenshot from 2021-11-29 18-17-40](https://user-images.githubusercontent.com/41812146/143858785-8b3a0f43-688c-4857-a4e6-7244b49c2411.png)
Please help me to fix this issue.

**Comment by bryonpokemon** [comment]
same, im trying to use sticky proxies to fix this but it doesnt work, keeps changing ip every request

**Comment by ngoctuanqt** [comment]
i got same error

**Comment by hathehuyen** [comment]
Same error in 2023, even with the gologin app
