### ISSUE TITLE
how to get the profile id?

### ISSUE THREAD

**Issue by medsghiri** [gologinapp/gologin#33]
Sorry, I know this is not the place for the question but I have to. How to get the profile id knowing I have multiple profiles in my gologin accounts

**Comment by NephilimLord** [comment]
Please use api docs on https://api.gologin.com/docs/
GET /browser/v2 method

**Comment by medsghiri** [comment]
@NephilimLord  Thank you so much for replying. I found the solution in the examples folder: example-create-profile.js. Also, you can find the id of the profile you already created at the end of the URL when you click on settings.
