### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'gologin_zeroprofile.zip'

### ISSUE THREAD

**Issue by kundan16239** [gologinapp/gologin#38]
How to fix this issue?
![WhatsApp Image 2022-02-05 at 9 50 42 PM](https://user-images.githubusercontent.com/86150290/152649837-e09b9d92-76f6-449d-8343-67898ea9ef5a.jpeg)

**Comment by kundan16239** [comment]
fixed now

**Comment by danbopes** [comment]
> fixed now

How?
