### ISSUE TITLE
Error : when I run profile in puppeteer or selenium, language settings have problem.

### ISSUE THREAD

**Issue by takenkp** [gologinapp/gologin#50]
when I run profile in puppeteer or selenium, the language settings are only displayed in the upper two settings.
And it doesn't change even if I set the language separately. 
like using options.addArguments("--lang=es"); .
how can I deal with it?

**Comment by takenkp** [comment]
yes I changed it as I wanted. But still the language is fixed at English.

**Comment by alexandivv** [comment]
> yes I changed it as I wanted. But still the language is fixed at English.

what is the meaning of "fixed"? where do you want to change it?

**Comment by takenkp** [comment]
I know how to change it within the GoLogin app, but I don't know how to use the other language setting while using Selenium or Perpeteer.

**Comment by alexandivv** [comment]
> I know how to change it within the GoLogin app, but I don't know how to use the other language setting while using Selenium or Perpeteer.

what language do you want to set?

**Comment by takenkp** [comment]
I would like to set as "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7"

**Comment by alexandivv** [comment]
> I would like to set as "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7"

when creating a profile in the "language" value, you need to specify "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7". The profile will have the desired language. To launch an orbit through selenium with the desired language, specify the value "--lang=ko" in the "spawnBrowser" method, as I wrote above.

**Comment by takenkp** [comment]
I already tired like below
params = [
        self.executablePath,
        '--remote-debugging-port='+str(self.port),
        '--user-data-dir='+self.profile_path, 
        '--password-store=basic', 
        '--tz='+tz, 
        '--gologin-profile='+self.profile_name, 
        '--lang=ko',
        ]    
but it didn't work for me.

**Comment by alexandivv** [comment]
> I already tired like below params = [ self.executablePath, '--remote-debugging-port='+str(self.port), '--user-data-dir='+self.profile_path, '--password-store=basic', '--tz='+tz, '--gologin-profile='+self.profile_name, '--lang=ko', ] but it didn't work for me.

did you set the language settings "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7" in your profile settings? i did it and it worked

**Comment by takenkp** [comment]
when I run profile on gologin app, profile have a correct lang what i want. but, it didnt work on puppeteer or selenium

**Comment by takenkp** [comment]
> > I already tired like below params = [ self.executablePath, '--remote-debugging-port='+str(self.port), '--user-data-dir='+self.profile_path, '--password-store=basic', '--tz='+tz, '--gologin-profile='+self.profile_name, '--lang=ko', ] but it didn't work for me.
> 
> did you set the language settings "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7" in your profile settings? i did it and it worked

I did but it didn't work on selenium or puppeteer.

**Comment by s0ckd3** [comment]
First you have to create a profile with the language you need from the Gologin APP or from the Puppeteer Source Code:

```os: 'win', // win, android, lin, mac ...
        googleServicesEnabled: false,
        lockEnabled: false,
navigator: {
            language: 'vi,vi-VN;q=0.9,en-US;q=0.8',
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36',
            resolution: '1920x1080',
            platform: 'win',
        },
        canvasMode:'noise',
        canvas: {
            "mode": 'noise' 
            },```


Next when starting the profile you need to add Args:
```args: [
        '--lang=vi',
        '--tz=Asia/Bangkok',
        '--no-first-run',
        '--no-sandbox',
        '--font-masking-mode=2',
        '--origin-trial-disabled-features=ConditionalFocus',
        '--password-store=basic',
        '--disable-encryption',
        '--disable-blink-features=AutomationControlled',
        '--disable-infobars',
        '--disable-notifications'
       
    ],```
