### ISSUE TITLE
I want my money back! I'm going to do the charge

### ISSUE THREAD

**Issue by 0x64696d61** [gologinapp/gologin#62]
Hello!

In June, 28 2022 I tryed to buy 1 month. At first I payed by the bank, payment failed. I payed by BTC. But after hour bank payment done too. I connected with the bank and asked to cancel the transaction. 

In July, 20 the bank said that it can do nothing and I will connect with payment recipient. So, I connected with support chat. I wrote about the problem and send payment screens. Operator said that the problem will be resolved. But nothing happen till today.
  
I want a refund.
Tell me please, when can I get my money?

![IMAGE 2022-08-05 23:23:08](https://user-images.githubusercontent.com/35697308/183157251-9b142ca6-c0f4-493a-b3a5-088e71c3a438.jpg)
!

**Comment by NephilimLord** [comment]
Please contact our support team via chat, provide them account info (email) and describe you issue. Usually we set second month for subscription.
