### ISSUE TITLE
Issue with Cookies

### ISSUE THREAD

**Issue by farsadf** [gologinapp/gologin#63]
It seems that the file inside `Default/Network/Cookies` doesn't correctly reflect the status of cookies (at least for Chrome browser this file is a valid SQLite database but is empty).

This file is referenced in the following lines:

- https://github.com/gologinapp/gologin/blob/master/gologin.js#L63
- https://github.com/gologinapp/gologin/blob/master/gologin.js#L72

With that said, there's Cookies file (a valid SQLite database that has proper content), I locally patched the `gologin.js` file to handle cookie uploading by using that file, and I'm wondering whether there's something that I don't know regarding this issue.

**Comment by NephilimLord** [comment]
Cookies have been updated. Please check again and create new topic if needed. Thanks.
