### ISSUE TITLE
Playwright with gologin

### ISSUE THREAD

**Issue by nguyenthanhtien** [gologinapp/gologin#64]
I have a project using Playwright, can you help me explain Gologin can integrate with Playwrightor not? How to implement that?
https://playwright.dev/

**Comment by groupdore** [comment]
https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp

**Comment by stepjet** [comment]
@nguyenthanhtien yes, you need to launch gologin profile first this way:
```javascript
const GoLogin = require('gologin')
const GL = new GoLogin({
    token: 'yU0token', //paste your gologin api token here
    profile_id: 'yU0Pr0f1leiD', //paste your profile id here
  });

const { status, wsUrl } = await GL.startRemote();
```

then connect playwright to launched profile [via **wsUrl**](https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect-over-cdp)


```javascript
browser = playwright.chromium.connect_over_cdp(wsUrl)
default_context = browser.contexts[0]
page = default_context.pages[0]
```

that's all, please let me know if you have any problems with this code

**Comment by groupdore** [comment]
@stepjet can gologin add automation like genlogin. i see they used https://vueflow.dev/examples/

**Comment by stepjet** [comment]
@groupdore currently no, 
but this feature is in development and will be released soon, 
stay tuned for upcoming releases

**Comment by Motivationking** [comment]
> @nguyenthanhtien yes, you need to launch gologin profile first this way:
> 
> ```js
> const GoLogin = require('gologin')
> const GL = new GoLogin({
>     token: 'yU0token', //paste your gologin api token here
>     profile_id: 'yU0Pr0f1leiD', //paste your profile id here
>   });
> 
> const { status, wsUrl } = await GL.startRemote();
> ```
> 
> then connect playwright to launched profile [via **wsUrl**](https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect-over-cdp)
> 
> ```js
> browser = playwright.chromium.connect_over_cdp(wsUrl)
> default_context = browser.contexts[0]
> page = default_context.pages[0]
> ```
> 
> that's all, please let me know if you have any problems with this code

this is not helpful, when we run user id's wsurl in this it launch two windows, one is in incognito which is running my script correctly and 2nd window just stay opned it doesn't.. i just stay there until i mannually close them..

**Comment by mariusz4044** [comment]
This simple code working for me.
 
`const launcher = await chromium.connectOverCDP(wsUrl);`
