### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:35261 when in headless mode

### ISSUE THREAD

**Issue by searchingforcode** [gologinapp/gologin#71]
Hello i cant start anything when using headless mode. I tried with the example amazon script but it shows same thing.. Is there any solution for this? 
```

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: connect ECONNREFUSED 127.0.0.1:35261
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1237:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 35261,
  attempts: 5
}

Node.js v18.4.0

```

**Comment by searchingforcode** [comment]
Any update on this?

**Comment by lazuardyk** [comment]
I have same issue. @searchingforcode Did you found any solution?

**Comment by gcrene18** [comment]
Having the same issue on MacOs ARM and Ubuntu; although it works fine on windows. @searchingforcode @lazuardyk Found any solution?

**Comment by goodsoftwaredev** [comment]
Any luck here?

**Comment by stepjet** [comment]
Hi! guys, please try out latest orbita. issue should be fixed there: 

[Lin](https://dev.gologin.app/linux/orbita-110.1.2.9-linux.zip) | [Win](https://dev.gologin.app/win32/orbita-110.1.2.9-win32.zip) | [Mac Intel](https://dev.gologin.app/darwin/orbita-110.1.2.9-darwin.zip) | [Mac M1](https://dev.gologin.app/darwin/orbita-110.1.2.9-m1.zip)

any feedback appreciated, thanks :pray:

**Comment by obryng** [comment]
> Hi! guys, please try out latest orbita. issue should be fixed there:
> 
> [Lin](https://dev.gologin.app/linux/orbita-110.1.2.9-linux.zip) | [Win](https://dev.gologin.app/win32/orbita-110.1.2.9-win32.zip) | [Mac Intel](https://dev.gologin.app/darwin/orbita-110.1.2.9-darwin.zip) | [Mac M1](https://dev.gologin.app/darwin/orbita-110.1.2.9-m1.zip)
> 
> any feedback appreciated, thanks 🙏

Same problem with the latest version

**Comment by thgiang** [comment]
Same problem, All are newest. I just download Go Login yesterday (09/2023)

**Comment by alvinlys** [comment]
you guys may try with below, mine works in ubuntu
```
const GL = new GoLogin({
    token: 'yU0token',
    profile_id: 'yU0Pr0f1leiD',
    extra_params: [
            '--no-sandbox'
     ]
  });

```

**Comment by Mhexlet** [comment]
The same problem, is there a solution?

**Comment by Mhexlet** [comment]
I solved the problem, hooray, look for the directory in the root folder.gologin and the orbit browser folder in it, there is an executable chrome file, try to run it and it will show you that there are not enough dependencies, install them and will)))

sudo apt-get install -y libatk1.0-0 libatk-bridge2.0-0 libcups2 libxcomposite1 libxrandr2 libxdamage1 libxfixes3 libxi6 libxtst6 libnss3 libgconf-2-4 libasound2 libpangocairo-1.0-0 libgtk-3-0

sudo apt-get install -y libgbm1
