### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by adam-simple** [gologinapp/gologin#91]
When using the vncPort option I get __dirname is not defined.

It looks related to this issue https://stackoverflow.com/questions/64383909/dirname-is-not-defined-error-in-node-14-version.

Should we add 

```
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
```

to gologin.js in order to be able to use __dirname for newer node versions?

**Comment by khoubeib-zembra** [comment]
I have the same issue. I am running the latest node docker image v21.4.0 and npm 10.2.4. How can I get this resolved?

**Comment by viniciuspatzer** [comment]
same here...

**Comment by NephilimLord** [comment]
has been fixed
