### ISSUE TITLE
util is not defined

### ISSUE THREAD

**Issue by stepjet** [gologinapp/gologin#93]
https://github.com/gologinapp/gologin/blob/1860882a856b70ce6e719832a1acb525875f4332/src/gologin.js#L24

ReferenceError util is not defined
![Issue](https://user-images.githubusercontent.com/8189590/225250752-52f6907d-b2d3-4ac4-b8fc-f9cf09c42115.jpg)

perhaps need to prepend with: 
```JavaScript
const util = require('util')
```

**Comment by NephilimLord** [comment]
has been fixed
